# Generated by Django 2.0.5 on 2018-11-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='バンド名')),
            ],
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='日程')),
                ('title', models.CharField(max_length=50, verbose_name='企画名')),
                ('place', models.CharField(max_length=30, verbose_name='ライブハウス')),
                ('open', models.DateTimeField(verbose_name='OPEN')),
                ('start', models.DateTimeField(verbose_name='START')),
                ('door', models.IntegerField(verbose_name='当日料金')),
                ('adv', models.IntegerField(verbose_name='前売料金')),
                ('band', models.ManyToManyField(to='livecalendar.Band', verbose_name='出演バンド')),
            ],
        ),
    ]
