# Generated by Django 2.0.5 on 2018-11-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livecalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='date',
            field=models.DateField(verbose_name='日程'),
        ),
        migrations.AlterField(
            model_name='live',
            name='open',
            field=models.TimeField(verbose_name='OPEN'),
        ),
        migrations.AlterField(
            model_name='live',
            name='start',
            field=models.TimeField(verbose_name='START'),
        ),
    ]
