# Generated by Django 2.0.5 on 2018-11-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livecalendar', '0002_auto_20181119_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='adv',
            field=models.IntegerField(blank=True, null=True, verbose_name='前売料金'),
        ),
        migrations.AlterField(
            model_name='live',
            name='band',
            field=models.ManyToManyField(blank=True, null=True, to='livecalendar.Band', verbose_name='出演バンド'),
        ),
        migrations.AlterField(
            model_name='live',
            name='door',
            field=models.IntegerField(blank=True, null=True, verbose_name='当日料金'),
        ),
        migrations.AlterField(
            model_name='live',
            name='open',
            field=models.TimeField(blank=True, null=True, verbose_name='OPEN'),
        ),
        migrations.AlterField(
            model_name='live',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='START'),
        ),
    ]
